### ISSUE TITLE
Wrong number of columns in SumMarize

### ISSUE THREAD

**Issue by olagosta** [gkumar09/iSeqQC#2]
The psych::describe function generates a shorter summary for large datasets, causing an error in line 53. That can be solved by adding the option `fast = FALSE` to describe(). 
Also in the same function, there's warnings caused by colSums(DF[,-1]) in add_sum and add_sum_zero. That lines (54 and 55) shouldn't use colSums(DF)?

**Comment by gkumar09** [comment]
Fixed...thanks
