### ISSUE TITLE
The function filtering_data returns error

### ISSUE THREAD

**Issue by pbiology** [gkumar09/iSeqQC#5]
I can't run the cli Rscript. I immediately  get an error from the function "filtering_data".:

> Error in `[.data.frame`(final_data_new, match(as.character(DF1$samples),  : 
>   undefined columns selected 

The headers of my input data looks as follow:

samples shortnames      groups  include
SRR5223500      500     treated TRUE
SRR5223505      505     control TRUE
SRR5223522      522     treated TRUE
SRR5223543      543     treated TRUE
SRR5223547      547     control TRUE
SRR5223570      570     control TRUE

gene_id SRR5223500      SRR5223505      SRR5223522      SRR5223543      SRR5223547      SRR5223570
ENSG00000000003 8       5       11      11      14      6
ENSG00000000419 123     159     125     129     185     134
ENSG00000000457 206     157     187     124     139     103
ENSG00000000460 31      29      34      34      39      40

**Comment by gkumar09** [comment]
I used the header of the file you provided- it runs perfectly. Are you running the command from 'iSeqQC_cli' dir. This is what I used:
Rscript --vanilla iSeqQC.R ~/Desktop/testmanifest.txt ~/Desktop/testcts.txt R ID H

Also, check if your column names doesn't have any unnecessary spaces

**Comment by pbiology** [comment]
Seems like there was an extra whitespace in one of the column names.
It is working now.

**Comment by gkumar09** [comment]
Awesome!
